# This file will be configured to contain variables for CPack. These variables
# should be set in the CMake list file of the project before CPack module is
# included. The list of available CPACK_xxx variables and their associated
# documentation may be obtained using
#  cpack --help-variable-list
#
# Some variables are common to all generators (e.g. CPACK_PACKAGE_NAME)
# and some are specific to a generator
# (e.g. CPACK_NSIS_EXTRA_INSTALL_COMMANDS). The generator specific variables
# usually begin with CPACK_<GENNAME>_xxxx.


SET(CPACK_BINARY_BUNDLE "")
SET(CPACK_BINARY_CYGWIN "")
SET(CPACK_BINARY_DEB "")
SET(CPACK_BINARY_DRAGNDROP "")
SET(CPACK_BINARY_NSIS "")
SET(CPACK_BINARY_OSXX11 "")
SET(CPACK_BINARY_PACKAGEMAKER "")
SET(CPACK_BINARY_RPM "")
SET(CPACK_BINARY_STGZ "")
SET(CPACK_BINARY_TBZ2 "")
SET(CPACK_BINARY_TGZ "")
SET(CPACK_BINARY_TZ "")
SET(CPACK_BINARY_WIX "")
SET(CPACK_BINARY_ZIP "")
SET(CPACK_CMAKE_GENERATOR "Unix Makefiles")
SET(CPACK_COMPONENT_UNSPECIFIED_HIDDEN "TRUE")
SET(CPACK_COMPONENT_UNSPECIFIED_REQUIRED "TRUE")
SET(CPACK_DEBIAN_PACKAGE_HOMEPAGE "http://www.html-tidy.org/")
SET(CPACK_DEBIAN_PACKAGE_MAINTAINER "maintainer@htacg.org")
SET(CPACK_DEBIAN_PACKAGE_SECTION "Libraries")
SET(CPACK_GENERATOR "TGZ")
SET(CPACK_IGNORE_FILES "/home/eewing/Twitch/tac/discordbot/libtidy/test/;/home/eewing/Twitch/tac/discordbot/libtidy/build/;/home/eewing/Twitch/tac/discordbot/libtidy/.git/")
SET(CPACK_INSTALLED_DIRECTORIES "/home/eewing/Twitch/tac/discordbot/libtidy;/")
SET(CPACK_INSTALL_CMAKE_PROJECTS "")
SET(CPACK_INSTALL_PREFIX "/usr/local")
SET(CPACK_MODULE_PATH "")
SET(CPACK_NSIS_DISPLAY_NAME "tidy 5.1.33")
SET(CPACK_NSIS_INSTALLER_ICON_CODE "")
SET(CPACK_NSIS_INSTALLER_MUI_ICON_CODE "")
SET(CPACK_NSIS_INSTALL_ROOT "$PROGRAMFILES")
SET(CPACK_NSIS_PACKAGE_NAME "tidy 5.1.33")
SET(CPACK_OUTPUT_CONFIG_FILE "/home/eewing/Twitch/tac/discordbot/libtidy/CPackConfig.cmake")
SET(CPACK_PACKAGE_CONTACT "maintainer@htacg.org")
SET(CPACK_PACKAGE_DEFAULT_LOCATION "/")
SET(CPACK_PACKAGE_DESCRIPTION_FILE "/home/eewing/Twitch/tac/discordbot/libtidy/README/README.html")
SET(CPACK_PACKAGE_DESCRIPTION_SUMMARY "tidy - HTML syntax checker")
SET(CPACK_PACKAGE_FILE_NAME "tidy-5.1.33-Source")
SET(CPACK_PACKAGE_INSTALL_DIRECTORY "tidy 5.1.33")
SET(CPACK_PACKAGE_INSTALL_REGISTRY_KEY "tidy 5.1.33")
SET(CPACK_PACKAGE_NAME "tidy")
SET(CPACK_PACKAGE_RELOCATABLE "true")
SET(CPACK_PACKAGE_VENDOR "HTML Tidy Advocacy Community Group")
SET(CPACK_PACKAGE_VERSION "5.1.33")
SET(CPACK_PACKAGE_VERSION_MAJOR "5")
SET(CPACK_PACKAGE_VERSION_MINOR "1")
SET(CPACK_PACKAGE_VERSION_PATCH "33")
SET(CPACK_RESOURCE_FILE_LICENSE "/home/eewing/Twitch/tac/discordbot/libtidy/README/LICENSE.txt")
SET(CPACK_RESOURCE_FILE_README "/home/eewing/Twitch/tac/discordbot/libtidy/README/README.html")
SET(CPACK_RESOURCE_FILE_WELCOME "/home/eewing/Twitch/tac/discordbot/libtidy/README/README.html")
SET(CPACK_SET_DESTDIR "OFF")
SET(CPACK_SOURCE_CYGWIN "")
SET(CPACK_SOURCE_GENERATOR "TGZ")
SET(CPACK_SOURCE_IGNORE_FILES "/home/eewing/Twitch/tac/discordbot/libtidy/test/;/home/eewing/Twitch/tac/discordbot/libtidy/build/;/home/eewing/Twitch/tac/discordbot/libtidy/.git/")
SET(CPACK_SOURCE_INSTALLED_DIRECTORIES "/home/eewing/Twitch/tac/discordbot/libtidy;/")
SET(CPACK_SOURCE_OUTPUT_CONFIG_FILE "/home/eewing/Twitch/tac/discordbot/libtidy/CPackSourceConfig.cmake")
SET(CPACK_SOURCE_PACKAGE_FILE_NAME "tidy-5.1.33-Source")
SET(CPACK_SOURCE_TBZ2 "")
SET(CPACK_SOURCE_TGZ "")
SET(CPACK_SOURCE_TOPLEVEL_TAG "Linux-Source")
SET(CPACK_SOURCE_TZ "")
SET(CPACK_SOURCE_ZIP "")
SET(CPACK_STRIP_FILES "")
SET(CPACK_SYSTEM_NAME "Linux")
SET(CPACK_TOPLEVEL_TAG "Linux-Source")
SET(CPACK_WIX_SIZEOF_VOID_P "8")
